name: Code Quality

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Set up sn-scratch
        run: sudo dpkg -i ./content/code-quality/sonar/github/sn-scratch/sn-scratch_1.0.0_all.deb
      - name: Run SonarQube
        run: sn-scratch new --name sonarqube:7.9.1-community ./content/code-quality/sonar/images
      - name: Wait SonarQube ready
        run: ./content/dist/linux/sn-scratch-ch.sh -c --sleep 10000
      - name: Build & Test & Analyze
        run: mvn -f ./content/pom.xml -B jacoco:prepare-agent test sonar:sonar
      - name: Check issues
        run: ./content/dist/linux/sn-scratch-ch.sh -r --path ./sonarqube-issues.html --project:org.sonarscratch.checker:sonarscratchchecker ./content
      - name: Upload report
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: sonarqube-issues
          path: ./sonarqube-issues.html
